title: Muskan Manwani
logo: https://github.com/Muskan-guelph/Credit_Card_Financial_Dashboard/blob/main/Assets/Images/Profile%20Pic.png?raw=true
show_downloads: True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
